// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210823215917_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            id = new Guid("a4a0fa99-a258-4bae-aef4-b272d1af5808"),
                            description = "Canal dedicado a dotnet core",
                            name = "DotnetCore"
                        },
                        new
                        {
                            id = new Guid("67c39dc7-847a-4f13-8de1-cd5d7f29d9b7"),
                            description = "Canal dedicado a Angular",
                            name = "Angular"
                        },
                        new
                        {
                            id = new Guid("7b57afbf-9505-4367-b7b4-fc1edb2a303d"),
                            description = "Canal dedicado a ReactJs",
                            name = "ReactJs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
